name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Clona tu repositorio
    - name: Set up JDK 23  # Cambia a JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'  # Usa Java 23
        distribution: 'temurin'
        cache: maven  # Cache para dependencias de Maven
    - name: Build with Maven
      run: mvn -B package --file UcoBet-Generales/pom.xml  # Aseg√∫rate de que esta ruta sea correcta

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

